//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_GioHang_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_GioHang_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Administrator\AppData\Local\Temp\799C5355F9F66D4E2E90EEE98292525EE540\2\LTWeb\DichVuThuCungKVH\Views\GioHang\GioHang.cshtml"
  
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 2 "C:\Users\Administrator\AppData\Local\Temp\799C5355F9F66D4E2E90EEE98292525EE540\2\LTWeb\DichVuThuCungKVH\Views\GioHang\GioHang.cshtml"
                __o = Url.Action("index","DVTC");


#line default
#line hidden
}
}
}
