//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhan_DichVu
    {
        public int MaPhieu { get; set; }
        public int MaDV { get; set; }
        public string DichVuSuDung { get; set; }
        public string NguoiThucHien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuNhan PhieuNhan { get; set; }
    }
}
