//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhan()
        {
            this.CTPhieuNhan_DichVu = new HashSet<CTPhieuNhan_DichVu>();
        }
    
        public int MaPhieu { get; set; }
        public Nullable<int> MaTC { get; set; }
        public Nullable<int> MaSDDV { get; set; }
        public string TinhTrangTruocTiepNhan { get; set; }
        public string TinhTrangSauTiepNhan { get; set; }
        public string NguoiGiao { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string TinhTrangDichVu { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string NguoiTra { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhan_DichVu> CTPhieuNhan_DichVu { get; set; }
        public virtual SuDungDichVu SuDungDichVu { get; set; }
        public virtual ThuCung ThuCung { get; set; }
    }
}
