//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThuCungKVH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuCung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuCung()
        {
            this.PhieuNhans = new HashSet<PhieuNhan>();
        }
    
        public int MaTC { get; set; }
        public int MaKH { get; set; }
        public string TenTC { get; set; }
        public string HinhAnh { get; set; }
        public string DacDiem { get; set; }
        public string Loai { get; set; }
        public string MauLong { get; set; }
        public string CanNang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhan> PhieuNhans { get; set; }
    }
}
